### model
model_name_or_path: Qwen/Qwen2.5-0.5B-Instruct

# #qlora
quantization_bit: 4
quantization_method: bitsandbytes # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]

trust_remote_code: true

### method

#what kind of training
# still provide dpo here even if you use rdpo
stage: dpo
#IMPORTANT if you use dpo, need to specify if RDPO or not! If dont specify, just normal DPO
rdpo: true
#true for training, false for eval
do_train: true
do_eval: false
#Fine-tuning method. Optional: freeze, lora, full
finetuning_type: lora
lora_rank: 1
lora_target: all
deepspeed: examples/deepspeed/ds_z2_config.json # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
pref_beta: 0.1
pref_loss: sigmoid # choices: [sigmoid (dpo), orpo, simpo]

#the hyperparam for our RDPO loss
# may need some investigation here to see the tuning for this
reasoning_weight: 0.5
#whether to normalize the reasoning logps or not
norm_reasoning: true

### dataset

#must exist locally, in the LlamaFactory dataset folder
#remember to use the RDPO dataset format
dataset: genrm_rdpo
#Dataset template, please ensure that the dataset template corresponds to the model.
# though i think this is just to format the dataset questions?
template: qwen
#this can significantly affect cuda memory use; reduce this if memory problems too much
# for rdpo, text is doubled so memory issues more prevalent
cutoff_len: 2
#subset of entire training set, for experimentation
# only use positive numbers here
# set it to the size of the dataset
max_samples: 10
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output_models/train-qwen2.5-0.5b-genrm-rdpo
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
gradient_checkpointing: true
per_device_train_batch_size: 2 #may need to reduce batch size since reasoning adds more data
#stores these gradients instead of immediately updating after every batch
#best to keep the same or increase
gradient_accumulation_steps: 1
learning_rate: 1.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
# #if youre quantizing model; probably not a good idea to run this
# pure_bf16: true
fp16: false
ddp_timeout: 180000000
flash_attn: fa2
